# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 18
        platform: x64

    - name: Verify Clang installation
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main"
        sudo apt update
        sudo apt-get install libc++-18-dev libc++abi-18-dev
        clang --version
        which clang

    - name: Install Ninja
      run: sudo apt-get install -y ninja-build
    
    - name: Configure CMake
      run: 
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja;

    - name: Build
      run: 
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}};

